[phases.setup]
nixPkgs = ["php83", "php83Extensions.intl", "php83Extensions.zip", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.pdo"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-reqs"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"