[phases.setup]
nixPkgs = ["php82", "php82Extensions.intl", "php82Extensions.zip", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.pdo"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"